local_costmap:
  global_frame: odom
  robot_base_frame: v1
  update_frequency: 2.0
  publish_frequency: 5.0
  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.05
  transform_tolerance: 10
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
